import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEmail,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';

export class SendBillingDocumentEmailDto {
  @ApiPropertyOptional({
    description:
      'Recipient email address. Falls back to snapshot.customer.email when omitted.',
    example: 'customer@example.com',
  })
  @IsOptional()
  @IsEmail()
  recipientEmail?: string;

  @ApiProperty({
    description: 'Base64-encoded PDF bytes generated by the client.',
  })
  @IsString()
  @MinLength(100)
  @MaxLength(10_000_000)
  pdfBase64: string;
}
